# Specify which configs to use.
defaults:
  - cluster: local  # Tells hydra to use cluster/local.yaml when composing the cfg object.
  - dataloader: era5
  - module: forecast-geoarchesweather
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_


# Wandb logging
log: False # Turn off and on wandb logging
entity:
project: ${module.project}
name: default

exp_dir: modelstore/${name} # Checkpoint dir
resume: True  # To resume a previous run, loads checkpoint and cfg from `exp_dir`.

seed: 0
max_steps: 300000
batch_size: ${cluster.batch_size}

save_step_frequency: 50000
log_freq: 100
limit_val_batches: null
accumulate_grad_batches: 1
debug: False # set to True to debug

mode: train  # Specify "train" or "test" to run training or inference.